### ISSUE TITLE
Create a MUI Menu

### ISSUE THREAD

**Issue by aarabii** [aarabii/chrome-homepage#1]
Add a menu that appears after clicking on the gear icon which will help user to customize the site on their own and their customisation should save locally

**Comment by kevinstewartsmith** [comment]
What items should be in the menu? Should the contributor add placeholder text for each item?

**Comment by aarabii** [comment]
some more valuable tools like chatGPT Dalee or anything or a section from where a user can add their shortcuts too like in Microsoft Edge
you can do anything with this though and your work will be appreciated
@kevinstewartsmith
